overrides:
- override_id: ACT_fa709bff2322
  review_id: REV_76b015181485
  fact_id: ''
  source_cell_ref: 债务人审计报告-2022年:4:aliyun_table:0:13-13:3-3
  row_label_std: 一年内到期长期债权投资
  row_label_raw: 一年内到期长期债权投资
  note: ''
  reviewer_name: tester
  action_type: ignore
  enabled: true
  task_id: REOCR_16b9e690e661
  target_id: REV_76b015181485
  target_scope: review_item
  config_file_touched: manual_overrides/placement_overrides.yml
- override_id: ACT_243aa078a25d
  review_id: REV_49c267aa9424
  fact_id: ''
  source_cell_ref: 债务人审计报告-2022年:4:aliyun_table:0:13-13:7-7
  row_label_std: 预计负债
  row_label_raw: 预计负债
  note: ''
  reviewer_name: tester
  action_type: ignore
  enabled: true
  task_id: REOCR_27e506875448
  target_id: REV_49c267aa9424
  target_scope: review_item
  config_file_touched: manual_overrides/placement_overrides.yml
- override_id: ACT_08b9497acb53
  review_id: REV_51cc89ca6fc1
  fact_id: ''
  source_cell_ref: 债务人审计报告-2022年:4:aliyun_table:0:18-18:3-3
  row_label_std: 长期债权投资
  row_label_raw: 长期债权投资
  note: ''
  reviewer_name: tester
  action_type: ignore
  enabled: true
  task_id: REOCR_e160af747198
  target_id: REV_51cc89ca6fc1
  target_scope: review_item
  config_file_touched: manual_overrides/placement_overrides.yml
- override_id: ACT_f1537f0c659c
  review_id: REV_dff68127a214
  fact_id: ''
  source_cell_ref: 债务人审计报告-2022年:4:aliyun_table:0:28-28:7-7
  row_label_std: ''
  row_label_raw: ''
  note: ''
  reviewer_name: tester
  action_type: ignore
  enabled: true
  task_id: REOCR_c5fd4cde7ca2
  target_id: REV_dff68127a214
  target_scope: review_item
  config_file_touched: manual_overrides/placement_overrides.yml
- override_id: ACT_345d1af1fecf
  review_id: REV_e4ecb90dd858
  fact_id: ''
  source_cell_ref: 债务人审计报告-2022年:4:aliyun_table:0:13-13:2-2
  row_label_std: 一年内到期长期债权投资
  row_label_raw: 一年内到期长期债权投资
  note: ''
  reviewer_name: tester
  action_type: ignore
  enabled: true
  task_id: REOCR_0297e8424eb4
  target_id: REV_e4ecb90dd858
  target_scope: review_item
  config_file_touched: manual_overrides/placement_overrides.yml
